version: '3.8'

services:
  postgres:
    image: postgres:10.3
    container_name: postgres
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
      POSTGRES_DB: byndies-sharing-local
    ports:
      - '5430:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
volumes:
  postgres: ~
